language: perl

perl:
 - "5.10"
 - "5.12"
 - "5.14"

install:
 - cpanm Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO
 - dzil listdeps --missing | cpanm

script:
 - dzil test --all

notifications:
  recipient:
   - al3xbio@gmail.com
  email:
    on_success: change
    on_failure: always
